### ISSUE TITLE
Crash when init RoomCaptureView

### ISSUE THREAD

**Issue by fpt-hungnx5** [markckim/RoomPlan#1]
Dear @markckim. I created demo with RoomCaptureView. But when init RoomCaptureView is failed.
Pls support me or send me your code!
Thank you so much!
Code:

private func setupRoomCaptureView() {
        roomCaptureView = RoomCaptureView(frame: view.bounds)
        roomCaptureView.captureSession.delegate = self
        roomCaptureView.delegate = self
        view.insertSubview(roomCaptureView, at: 0)
    }

**Comment by markckim** [comment]
What's the error message?

It sounds like you're trying to use RoomCaptureView which is on the non-data API side of things -- I haven't experimented with that much, unfortunately.

**Comment by xiaoqib** [comment]
![image](https://user-images.githubusercontent.com/12532549/179441929-3705e722-d4e0-44c1-bd28-d11259f725c3.png)
I also failed to initialize.

**Comment by markckim** [comment]
@xiaoqib Hey, very sorry about this. I didn't realize my github repo had missing files. I've restored all the missing files. Feel free to let me know if you see any more issues.

**Comment by xiaoqib** [comment]
That's cool. I'm working on how to replace the furniture. Do you have any ideas

**Comment by markckim** [comment]
@xiaoqib I would say replacing the real furniture in the scene is non-trivial.

That being said, here's a tweet where someone was able to do this:
* https://twitter.com/strangenative/status/1547227797793284096?s=21&t=Qun_xtGRj7a25xU6C59sSw

It involves using RoomPlan data of `CapturedRoom` surfaces, using Photoshop (or similar tool) to fill in the missing surface textures behind/under the real furniture that RoomPlan cannot see, and (likely) exporting the texture to a 3D graphics engine like Metal (or OpenGL) to render the empty room.

**Comment by xiaoqib** [comment]
@markckim Yeah I saw the video too, unfortunately I don't know how they do it, I'm trying some solutions on my own.Thanks again for fixing your code

**Comment by markckim** [comment]
@xiaoqib They are not sharing a lot of details. They're mainly using RoomPlan data api to populate `CapturedRoom` object which has all the data for room object (e.g., sofa, table, etc.) and surface (walls, etc.) positions and dimensions.

Once they have that data, they no longer use ARKit or RoomPlan. They use the data within `CapturedRoom` to render the room in 3D.

I'll add that there is likely no 'easy' way to replace the furniture. It will likely require 3D graphics knowledge. Would be happy to hear if there you do find a good solution.
